name: learn_to_talk
description: "On-device language learning app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # UI components
  flutter_tts: ^3.8.5
  # Simple on-device speech recognition that works without cloud credentials
  speech_to_text: ^7.0.0
  # Audio processing
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  lottie: ^2.6.0
  
  # ML Kit for on-device translation
  google_mlkit_translation: ^0.9.0
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utils
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  # Logging
  logging: ^1.2.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
